### PR TITLE
Image name case insensitive enable

### PR DESCRIPTION
**Pull request by josefzajac**
Hi,
Is lowercase extension mandatory?

### CODE REVIEW

**Comment by davidkudera** [comment]
Hi and thank you. 

To answer your question, I think it shouldn't be. But will it be enough to test it just here? What do you think about for example automatically converting extensions to lower case when saving new images?

**Comment by josefzajac** [comment]
It can't be automatically inside-the-box (ImageManager), otherwise there will be inconsistent values on input and output in some use-cases.
eq:
$name = $formValues->image->name; // = new_image.JPG
$galleryImageEntity->setImageName($name);

$imagesManager->upload($values->image->toImage(), $image->getNamespace(), $name);
// if $name will be lowercased inside upload method, there will be different imageName in $galleryImageEntity.

Manager usage should be in updated and it is not Backward-Compatible :/ depends on specific usage, which we can't guarantee. It is already in examples and documentation, I see more risks then advantages. 
$newImage = $imagesManager->upload($values->image->toImage(), $image->getNamespace(), $name);
$galleryImageEntity->setImageName($newImage->name);

PS: Zdravim z Prahy :)

**Comment by davidkudera** [comment]
Oh you're right. So is this the only place which needs to be updated? Because if it is, I'll definitelly merge it ;-)

Taky zdravím a pěkný nový rok :beers:

**Comment by davidkudera** [comment]
Sorry, I totaly forgot.... And thanks

**Pull request merged**
